# Generated by Django 4.1 on 2022-08-22 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import title_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='Обложка')),
                ('background', models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='Фон')),
                ('origin_name', models.CharField(max_length=100, unique=True, verbose_name='Оригинальное название (без иероглифов)')),
                ('russian_name', models.CharField(blank=True, max_length=100, null=True, validators=[title_app.validators.validate_russian], verbose_name='Русское название')),
                ('english_name', models.CharField(blank=True, max_length=100, null=True, validators=[title_app.validators.validate_english], verbose_name='Английское название')),
                ('alternative_names', models.CharField(blank=True, max_length=500, null=True, verbose_name='Альтернативные названия (с иероглифами)')),
                ('title_type', models.CharField(blank=True, choices=[('manga', 'Манга'), ('manhwa', 'Манхва'), ('manhua', 'Маньхуа'), ('rumanga', 'Руманга'), ('OEL-manga', 'OEL-манга'), ('comic', 'Западный комикс')], default='manga', max_length=10, null=True, verbose_name='Тип')),
                ('release_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год релиза')),
                ('title_url', models.SlugField(unique=True, verbose_name='урл манги')),
                ('release_format', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('4-koma', '4-кома (Ёнкома)'), ('in color', 'В цвете'), ('web', 'Веб'), ('webtoon', 'Вебтун'), ('doujinshi', 'Додзинси'), ('manga collection', 'Сборник'), ('single', 'Сингл')], max_length=50, null=True, verbose_name='Формат выпуска')),
                ('title_status', models.CharField(blank=True, choices=[('ongoing', 'Онгоинг'), ('finish', 'Завершён'), ('anons', 'Анонс'), ('stopped', 'Приостановлен'), ('discontinued', 'Выпуск прекращён')], max_length=50, null=True, verbose_name='Статус тайтла')),
                ('translator_status', models.CharField(blank=True, choices=[('continued', 'Продолжается'), ('finished', 'Завершён'), ('frozen', 'Замарожен'), ('abandoned', 'Заброшен')], max_length=50, null=True, verbose_name='Статус перевода')),
                ('adult_content', models.CharField(blank=True, choices=[('no', 'Нет'), ('yes 16+', 'Да 16+'), ('Yes 18+', 'Да 18+')], max_length=50, null=True, verbose_name='Контент для взрослых')),
                ('download_chapter', models.CharField(blank=True, choices=[('All', 'Все'), ('Only', 'Создатель и Переводчики')], max_length=50, null=True, verbose_name='Загрузка глав')),
                ('links_to_original', models.URLField(blank=True, null=True, verbose_name='Ссылки на оригинал или анлейт (помогает модерации)')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('artist', models.ManyToManyField(blank=True, related_name='artist', to='admin_panel_app.person', verbose_name='Художник')),
                ('author', models.ManyToManyField(blank=True, related_name='author', to='admin_panel_app.person', verbose_name='Автор')),
                ('genres', models.ManyToManyField(blank=True, to='title_app.genre', verbose_name='Жанр')),
                ('publisher', models.ManyToManyField(blank=True, related_name='publisher', to='admin_panel_app.person', verbose_name='Издатель')),
                ('tags', models.ManyToManyField(blank=True, to='title_app.tag', verbose_name='Теги')),
                ('translators', models.ManyToManyField(blank=True, to='admin_panel_app.team', verbose_name='Переводчики')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тайтл',
                'verbose_name_plural': 'Тайтлы',
            },
        ),
    ]
