# Generated by Django 4.1 on 2022-09-05 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='user',
        ),
        migrations.AddField(
            model_name='title',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
