# Generated by Django 4.1 on 2022-09-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title_app', '0004_ratingstatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingStatistic',
        ),
    ]
