# Generated by Django 4.1.1 on 2023-05-29 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Свяжитесь с нами')),
                ('url2', models.URLField(blank=True, null=True, verbose_name='Свяжитесь с нами')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=60, unique=True, verbose_name='Имя на английском (без иероглифов)')),
                ('russian_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Имя на русском')),
                ('alternative_names', models.CharField(blank=True, max_length=255, null=True, verbose_name='Известен так же под именем')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person', verbose_name='Файл или изображение')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='Обложка')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('team_url', models.SlugField(unique=True, verbose_name='урл команды')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('vk', models.URLField(blank=True, null=True, verbose_name='Группа VK')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('discord', models.URLField(blank=True, null=True, verbose_name='Discord сервер')),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='УЧАСТНИКИ')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, null=True, upload_to='news', verbose_name='Файл или изображение')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ответ')),
                ('photo', models.FileField(blank=True, null=True, upload_to='FAQ photos', verbose_name='Файл или изображение')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel_app.topic', verbose_name='Тема')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
