# Generated by Django 4.1.1 on 2022-09-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportAuto',
            new_name='ReportManga',
        ),
    ]
