# Generated by Django 4.1 on 2022-08-27 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', multiselectfield.db.fields.MultiSelectField(choices=[('same genres', 'По жанрам'), ('same panache', 'По рисовке'), ('same plot', 'По сюжету')], max_length=25, verbose_name='Выбрать критерий схожести (макс. 2)')),
                ('similar_count', models.IntegerField(default=0)),
                ('main_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_titles', to='title_app.title', verbose_name='Главный тайтл ')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_title', to='title_app.title', verbose_name='Похожий тайтл')),
            ],
            options={
                'verbose_name': 'Похожее',
                'verbose_name_plural': 'Похожее',
                'unique_together': {('main_title', 'title')},
            },
        ),
        migrations.CreateModel(
            name='SimilarLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='info_section_app.similartitle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='info_section_app.similartitle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
