# Generated by Django 4.1 on 2022-08-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_section_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similartitle',
            name='similar_count',
            field=models.IntegerField(),
        ),
    ]
