# Generated by Django 4.1 on 2022-09-01 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title_app', '0001_initial'),
        ('info_section_app', '0005_remove_similartitle_similar_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_type', models.CharField(choices=[('adaptation', 'Адаптация'), ('origin', 'Источник'), ('backstory', 'Предыстория'), ('continuation', 'Продолжение'), ('alternative history', 'Альтернативная история'), ('spin-off', 'Спин-офф'), ('crossover', 'Кроссовер'), ('color version', 'Цветная версия'), ('restart', 'Перезапуск'), ('another', 'Другое')], max_length=50, verbose_name='Тип связи')),
                ('main_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_titles', to='title_app.title', verbose_name='Главный тайтл ')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_title', to='title_app.title', verbose_name='Связанный тайтл')),
            ],
            options={
                'verbose_name': 'Связанное',
                'verbose_name_plural': 'Связанное',
                'unique_together': {('main_title', 'title')},
            },
        ),
    ]
