# Generated by Django 4.1 on 2022-09-05 07:53

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title_app', '0002_remove_title_user_title_user'),
        ('info_section_app', '0006_relatedtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedtitle',
            name='user',
            field=models.ManyToManyField(related_name='related_title_owners', to=settings.AUTH_USER_MODEL, verbose_name='пользователи'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название вкладки')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_owner', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Вкладка',
                'verbose_name_plural': 'Вкладки',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_folder', to='info_section_app.folder', verbose_name='вкладка')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_list', to='title_app.title', verbose_name='тайтл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'В списках',
                'verbose_name_plural': 'В списках',
                'unique_together': {('user', 'title')},
            },
        ),
    ]
