# Generated by Django 4.1 on 2022-09-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_section_app', '0008_alter_favorite_folder_delete_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='folder',
            field=models.CharField(choices=[('Читаю', 'Читаю'), ('Прочитано', 'Прочитано'), ('Брошено', 'Брошено'), ('В планах', 'В планах'), ('Любимые', 'Любимые')], max_length=255, verbose_name='вкладка'),
        ),
    ]
